// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Scrape struct {
	ID          int64
	RequestHash string
	Url         string
	Method      string
	Content     string
	Metadata    string
	CreatedAt   time.Time
}

type UsageLog struct {
	ID        int64
	Provider  string
	Engine    string
	Action    string
	Query     string
	Url       string
	Credits   int64
	CreatedAt time.Time
}
