// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Scrape struct {
	ID          int64
	RequestHash string
	Url         string
	Method      string
	Content     string
	Metadata    string
	CreatedAt   time.Time
}
