// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const clearCache = `-- name: ClearCache :exec
DELETE FROM scrapes
`

func (q *Queries) ClearCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCache)
	return err
}

const deleteOldVersions = `-- name: DeleteOldVersions :exec
DELETE FROM scrapes
WHERE scrapes.request_hash = ?
AND scrapes.id NOT IN (
    SELECT s2.id FROM (
        SELECT s3.id FROM scrapes s3
        WHERE s3.request_hash = ?
        ORDER BY s3.created_at DESC, s3.id DESC
        LIMIT ?
    ) s2
)
`

type DeleteOldVersionsParams struct {
	RequestHash   string
	RequestHash_2 string
	Limit         int64
}

func (q *Queries) DeleteOldVersions(ctx context.Context, arg DeleteOldVersionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldVersions, arg.RequestHash, arg.RequestHash_2, arg.Limit)
	return err
}

const getHistoryByUrl = `-- name: GetHistoryByUrl :many
SELECT id, request_hash, url, method, content, metadata, created_at FROM scrapes
WHERE url = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) GetHistoryByUrl(ctx context.Context, url string) ([]Scrape, error) {
	rows, err := q.db.QueryContext(ctx, getHistoryByUrl, url)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrape
	for rows.Next() {
		var i Scrape
		if err := rows.Scan(
			&i.ID,
			&i.RequestHash,
			&i.Url,
			&i.Method,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestScrape = `-- name: GetLatestScrape :one
SELECT id, request_hash, url, method, content, metadata, created_at FROM scrapes
WHERE request_hash = ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestScrape(ctx context.Context, requestHash string) (Scrape, error) {
	row := q.db.QueryRowContext(ctx, getLatestScrape, requestHash)
	var i Scrape
	err := row.Scan(
		&i.ID,
		&i.RequestHash,
		&i.Url,
		&i.Method,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getStats = `-- name: GetStats :one
SELECT
    COUNT(*) as total_count,
    SUM(length(content)) as total_size_bytes
FROM scrapes
`

type GetStatsRow struct {
	TotalCount     int64
	TotalSizeBytes sql.NullFloat64
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(&i.TotalCount, &i.TotalSizeBytes)
	return i, err
}

const getUsageByProvider = `-- name: GetUsageByProvider :many
SELECT provider, action,
       COUNT(*) as count,
       SUM(credits) as total_credits
FROM usage_log
WHERE created_at >= ?
GROUP BY provider, action
ORDER BY provider, action
`

type GetUsageByProviderRow struct {
	Provider     string
	Action       string
	Count        int64
	TotalCredits sql.NullFloat64
}

func (q *Queries) GetUsageByProvider(ctx context.Context, createdAt time.Time) ([]GetUsageByProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsageByProvider, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsageByProviderRow
	for rows.Next() {
		var i GetUsageByProviderRow
		if err := rows.Scan(
			&i.Provider,
			&i.Action,
			&i.Count,
			&i.TotalCredits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSince = `-- name: GetUsageSince :many
SELECT id, provider, engine, "action", "query", url, credits, created_at FROM usage_log
WHERE created_at >= ?
ORDER BY created_at DESC
`

func (q *Queries) GetUsageSince(ctx context.Context, createdAt time.Time) ([]UsageLog, error) {
	rows, err := q.db.QueryContext(ctx, getUsageSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageLog
	for rows.Next() {
		var i UsageLog
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Engine,
			&i.Action,
			&i.Query,
			&i.Url,
			&i.Credits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageTotal = `-- name: GetUsageTotal :one
SELECT COUNT(*) as total_count,
       SUM(credits) as total_credits
FROM usage_log
WHERE created_at >= ?
`

type GetUsageTotalRow struct {
	TotalCount   int64
	TotalCredits sql.NullFloat64
}

func (q *Queries) GetUsageTotal(ctx context.Context, createdAt time.Time) (GetUsageTotalRow, error) {
	row := q.db.QueryRowContext(ctx, getUsageTotal, createdAt)
	var i GetUsageTotalRow
	err := row.Scan(&i.TotalCount, &i.TotalCredits)
	return i, err
}

const insertScrape = `-- name: InsertScrape :one
INSERT INTO scrapes (
    request_hash, url, method, content, metadata
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, request_hash, url, method, content, metadata, created_at
`

type InsertScrapeParams struct {
	RequestHash string
	Url         string
	Method      string
	Content     string
	Metadata    string
}

func (q *Queries) InsertScrape(ctx context.Context, arg InsertScrapeParams) (Scrape, error) {
	row := q.db.QueryRowContext(ctx, insertScrape,
		arg.RequestHash,
		arg.Url,
		arg.Method,
		arg.Content,
		arg.Metadata,
	)
	var i Scrape
	err := row.Scan(
		&i.ID,
		&i.RequestHash,
		&i.Url,
		&i.Method,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertUsage = `-- name: InsertUsage :exec
INSERT INTO usage_log (provider, engine, action, query, url, credits)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertUsageParams struct {
	Provider string
	Engine   string
	Action   string
	Query    string
	Url      string
	Credits  int64
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) error {
	_, err := q.db.ExecContext(ctx, insertUsage,
		arg.Provider,
		arg.Engine,
		arg.Action,
		arg.Query,
		arg.Url,
		arg.Credits,
	)
	return err
}
